import { EditorElement } from "../types/global.types";

export const elements: EditorElement[] = [
  { title: "Heading 1", type: "h1", category: "Text" },
  { title: "Heading 2", type: "h2", category: "Text" },
  { title: "Heading 3", type: "h3", category: "Text" },
  { title: "Heading 4", type: "h4", category: "Text" },
  { title: "Heading 5", type: "h5", category: "Text" },
  { title: "Heading 6", type: "h6", category: "Text" },
  { title: "Paragraph", type: "p", category: "Text" },
  { title: "Bold", type: "b", category: "Text Formatting" },
  { title: "Italic", type: "i", category: "Text Formatting" },
  { title: "Underline", type: "u", category: "Text Formatting" },
  { title: "Strong", type: "strong", category: "Text Formatting" },
  { title: "Emphasis", type: "em", category: "Text Formatting" },
  { title: "Mark", type: "mark", category: "Text Formatting" },
  { title: "Small", type: "small", category: "Text Formatting" },
  { title: "Deleted Text", type: "del", category: "Text Formatting" },
  { title: "Inserted Text", type: "ins", category: "Text Formatting" },
  { title: "Subscript", type: "sub", category: "Text Formatting" },
  { title: "Superscript", type: "sup", category: "Text Formatting" },
  { title: "Link", type: "a", category: "Navigation" },
  { title: "Unordered List", type: "ul", category: "Structure" },
  { title: "Ordered List", type: "ol", category: "Structure" },
  { title: "List Item", type: "li", category: "Structure" },
  { title: "Definition List", type: "dl", category: "Structure" },
  { title: "Definition Term", type: "dt", category: "Structure" },
  { title: "Definition Description", type: "dd", category: "Structure" },
  { title: "Image", type: "img", category: "Media" },
  { title: "Audio", type: "audio", category: "Media" },
  { title: "Source", type: "source", category: "Media" },
  { title: "Video", type: "video", category: "Media" },
  { title: "Track", type: "track", category: "Media" },
  { title: "Form", type: "form", category: "Forms" },
  { title: "Input", type: "input", category: "Forms" },
  { title: "Textarea", type: "textarea", category: "Forms" },
  { title: "Button", type: "button", category: "Forms" },
  { title: "Select", type: "select", category: "Forms" },
  { title: "Option", type: "option", category: "Forms" },
  { title: "Label", type: "label", category: "Forms" },
  { title: "Fieldset", type: "fieldset", category: "Forms" },
  { title: "Legend", type: "legend", category: "Forms" },
  { title: "Table", type: "table", category: "Structure" },
  { title: "Table Head", type: "thead", category: "Structure" },
  { title: "Table Body", type: "tbody", category: "Structure" },
  { title: "Table Footer", type: "tfoot", category: "Structure" },
  { title: "Table Row", type: "tr", category: "Structure" },
  { title: "Table Header", type: "th", category: "Structure" },
  { title: "Table Data", type: "td", category: "Structure" },
  { title: "Caption", type: "caption", category: "Structure" },
  { title: "Column Group", type: "colgroup", category: "Structure" },
  { title: "Column", type: "col", category: "Structure" },
  { title: "Header", type: "header", category: "Layout" },
  { title: "Navigation", type: "nav", category: "Layout" },
  { title: "Main", type: "main", category: "Layout" },
  { title: "Footer", type: "footer", category: "Layout" },
  { title: "Section", type: "section", category: "Layout" },
  { title: "Article", type: "article", category: "Layout" },
  { title: "Aside", type: "aside", category: "Layout" },
  { title: "Span", type: "span", category: "Structure" },
  { title: "Div", type: "div", category: "Structure" },
  { title: "Details", type: "details", category: "Interactive" },
  { title: "Dialog", type: "dialog", category: "Interactive" },
  { title: "Summary", type: "summary", category: "Interactive" },
  { title: "Meta", type: "meta", category: "Head" },
  { title: "Link", type: "link", category: "Head" },
  { title: "Style", type: "style", category: "Head" },
  { title: "Script", type: "script", category: "Head" },
  { title: "Title", type: "title", category: "Head" },
  { title: "Base", type: "base", category: "Head" },
  { title: "Iframe", type: "iframe", category: "Media" },
  { title: "Embed", type: "embed", category: "Media" },
  { title: "Object", type: "object", category: "Media" },
  { title: "Param", type: "param", category: "Media" },
  { title: "Canvas", type: "canvas", category: "Graphics" },
  { title: "SVG", type: "svg", category: "Graphics" },
  { title: "Path", type: "path", category: "Graphics" },
  { title: "Circle", type: "circle", category: "Graphics" },
  { title: "Rect", type: "rect", category: "Graphics" },
  { title: "Line", type: "line", category: "Graphics" },
  { title: "Polyline", type: "polyline", category: "Graphics" },
  { title: "Polygon", type: "polygon", category: "Graphics" },
  { title: "Group", type: "g", category: "Graphics" },
];
