import { HtmlElement } from "../types/global.types";

export const elements: HtmlElement[] = [
  {
    title: "Heading 1",
    type: "h1",
    category: "Text",
    subCategory: "TextInput",
  },
  {
    title: "Heading 2",
    type: "h2",
    category: "Text",
    subCategory: "TextInput",
  },
  {
    title: "Heading 3",
    type: "h3",
    category: "Text",
    subCategory: "TextInput",
  },
  {
    title: "Heading 4",
    type: "h4",
    category: "Text",
    subCategory: "TextInput",
  },
  {
    title: "Heading 5",
    type: "h5",
    category: "Text",
    subCategory: "TextInput",
  },
  {
    title: "Heading 6",
    type: "h6",
    category: "Text",
    subCategory: "TextInput",
  },
  { title: "Paragraph", type: "p", category: "Text", subCategory: "TextInput" },
  // {
  //   title: "Bold",
  //   type: "b",
  //   category: "Text Formatting",
  //   subCategory: "None",
  // },
  // {
  //   title: "Italic",
  //   type: "i",
  //   category: "Text Formatting",
  //   subCategory: "None",
  // },
  // {
  //   title: "Underline",
  //   type: "u",
  //   category: "Text Formatting",
  //   subCategory: "None",
  // },
  // {
  //   title: "Strong",
  //   type: "strong",
  //   category: "Text Formatting",
  //   subCategory: "None",
  // },
  // {
  //   title: "Emphasis",
  //   type: "em",
  //   category: "Text Formatting",
  //   subCategory: "None",
  // },
  // {
  //   title: "Mark",
  //   type: "mark",
  //   category: "Text Formatting",
  //   subCategory: "None",
  // },
  // {
  //   title: "Small",
  //   type: "small",
  //   category: "Text Formatting",
  //   subCategory: "None",
  // },
  // {
  //   title: "Deleted Text",
  //   type: "del",
  //   category: "Text Formatting",
  //   subCategory: "None",
  // },
  // {
  //   title: "Inserted Text",
  //   type: "ins",
  //   category: "Text Formatting",
  //   subCategory: "None",
  // },
  // {
  //   title: "Subscript",
  //   type: "sub",
  //   category: "Text Formatting",
  //   subCategory: "None",
  // },
  // {
  //   title: "Superscript",
  //   type: "sup",
  //   category: "Text Formatting",
  //   subCategory: "None",
  // },
  {
    title: "Link",
    type: "a",
    category: "Navigation",
    subCategory: "TextInput",
  },
  {
    title: "Unordered List",
    type: "ul",
    category: "Structure",
    subCategory: "None",
  },
  {
    title: "Ordered List",
    type: "ol",
    category: "Structure",
    subCategory: "None",
  },
  {
    title: "List Item",
    type: "li",
    category: "Structure",
    subCategory: "TextInput",
  },
  {
    title: "Definition List",
    type: "dl",
    category: "Structure",
    subCategory: "None",
  },
  {
    title: "Definition Term",
    type: "dt",
    category: "Structure",
    subCategory: "TextInput",
  },
  {
    title: "Definition Description",
    type: "dd",
    category: "Structure",
    subCategory: "TextInput",
  },
  { title: "Image", type: "img", category: "Media", subCategory: "None" },
  { title: "Audio", type: "audio", category: "Media", subCategory: "None" },
  { title: "Source", type: "source", category: "Media", subCategory: "None" },
  { title: "Video", type: "video", category: "Media", subCategory: "None" },
  { title: "Track", type: "track", category: "Media", subCategory: "None" },
  { title: "Form", type: "form", category: "Forms", subCategory: "None" },
  {
    title: "Input",
    type: "input",
    category: "Forms",
    subCategory: "TextInput",
  },
  {
    title: "Textarea",
    type: "textarea",
    category: "Forms",
    subCategory: "TextInput",
  },
  { title: "Button", type: "button", category: "Forms", subCategory: "None" },
  { title: "Select", type: "select", category: "Forms", subCategory: "None" },
  {
    title: "Option",
    type: "option",
    category: "Forms",
    subCategory: "TextInput",
  },
  {
    title: "Label",
    type: "label",
    category: "Forms",
    subCategory: "TextInput",
  },
  {
    title: "Fieldset",
    type: "fieldset",
    category: "Forms",
    subCategory: "None",
  },
  {
    title: "Legend",
    type: "legend",
    category: "Forms",
    subCategory: "TextInput",
  },
  { title: "Table", type: "table", category: "Structure", subCategory: "None" },
  {
    title: "Table Head",
    type: "thead",
    category: "Structure",
    subCategory: "None",
  },
  {
    title: "Table Body",
    type: "tbody",
    category: "Structure",
    subCategory: "None",
  },
  {
    title: "Table Footer",
    type: "tfoot",
    category: "Structure",
    subCategory: "None",
  },
  {
    title: "Table Row",
    type: "tr",
    category: "Structure",
    subCategory: "None",
  },
  {
    title: "Table Header",
    type: "th",
    category: "Structure",
    subCategory: "TextInput",
  },
  {
    title: "Table Data",
    type: "td",
    category: "Structure",
    subCategory: "TextInput",
  },
  {
    title: "Caption",
    type: "caption",
    category: "Structure",
    subCategory: "TextInput",
  },
  {
    title: "Column Group",
    type: "colgroup",
    category: "Structure",
    subCategory: "None",
  },
  { title: "Column", type: "col", category: "Structure", subCategory: "None" },
  {
    title: "Header",
    type: "header",
    category: "Layout",
    subCategory: "TextInput",
  },
  { title: "Navigation", type: "nav", category: "Layout", subCategory: "None" },
  { title: "Main", type: "main", category: "Layout", subCategory: "None" },
  { title: "Footer", type: "footer", category: "Layout", subCategory: "None" },
  {
    title: "Section",
    type: "section",
    category: "Layout",
    subCategory: "TextInput",
  },
  {
    title: "Article",
    type: "article",
    category: "Layout",
    subCategory: "TextInput",
  },
  {
    title: "Aside",
    type: "aside",
    category: "Layout",
    subCategory: "TextInput",
  },
  {
    title: "Span",
    type: "span",
    category: "Structure",
    subCategory: "TextInput",
  },
  { title: "Div", type: "div", category: "Structure", subCategory: "None" },
  {
    title: "Details",
    type: "details",
    category: "Interactive",
    subCategory: "None",
  },
  {
    title: "Dialog",
    type: "dialog",
    category: "Interactive",
    subCategory: "None",
  },
  {
    title: "Summary",
    type: "summary",
    category: "Interactive",
    subCategory: "TextInput",
  },
  { title: "Meta", type: "meta", category: "Head", subCategory: "None" },
  { title: "Link", type: "link", category: "Head", subCategory: "None" },
  { title: "Style", type: "style", category: "Head", subCategory: "None" },
  { title: "Script", type: "script", category: "Head", subCategory: "None" },
  { title: "Title", type: "title", category: "Head", subCategory: "TextInput" },
  { title: "Base", type: "base", category: "Head", subCategory: "None" },
  { title: "Iframe", type: "iframe", category: "Media", subCategory: "None" },
  { title: "Embed", type: "embed", category: "Media", subCategory: "None" },
  { title: "Object", type: "object", category: "Media", subCategory: "None" },
  { title: "Param", type: "param", category: "Media", subCategory: "None" },
  {
    title: "Canvas",
    type: "canvas",
    category: "Graphics",
    subCategory: "None",
  },
  { title: "SVG", type: "svg", category: "Graphics", subCategory: "None" },
  { title: "Path", type: "path", category: "Graphics", subCategory: "None" },
  {
    title: "Circle",
    type: "circle",
    category: "Graphics",
    subCategory: "None",
  },
  { title: "Rect", type: "rect", category: "Graphics", subCategory: "None" },
  { title: "Line", type: "line", category: "Graphics", subCategory: "None" },
  {
    title: "Polyline",
    type: "polyline",
    category: "Graphics",
    subCategory: "None",
  },
  {
    title: "Polygon",
    type: "polygon",
    category: "Graphics",
    subCategory: "None",
  },
];
