export const tailwindClasses = {
  layout: [
    {
      class: "container",
      description: "Set the max-width based on screen size",
    },
    { class: "flex", description: "Create a flex container" },
    { class: "grid", description: "Create a grid container" },
    { class: "hidden", description: "Set display: none" },
    { class: "block", description: "Set display: block" },
    { class: "relative", description: "Set position: relative" },
    { class: "absolute", description: "Set position: absolute" },
  ],
  spacing: [
    { class: "p-1", description: "Padding: 0.25rem" },
    { class: "p-2", description: "Padding: 0.5rem" },
    { class: "p-4", description: "Padding: 1rem" },
    { class: "p-8", description: "Padding: 2rem" },
    { class: "m-1", description: "Margin: 0.25rem" },
    { class: "m-2", description: "Margin: 0.5rem" },
    { class: "m-4", description: "Margin: 1rem" },
    { class: "m-8", description: "Margin: 2rem" },
  ],
  typography: [
    { class: "text-sm", description: "Font size: 0.875rem" },
    { class: "text-base", description: "Font size: 1rem" },
    { class: "text-lg", description: "Font size: 1.125rem" },
    { class: "text-xl", description: "Font size: 1.25rem" },
    { class: "font-normal", description: "Font weight: 400" },
    { class: "font-medium", description: "Font weight: 500" },
    { class: "font-bold", description: "Font weight: 700" },
  ],
  colors: [
    { class: "text-gray-500", description: "Text color: Gray 500" },
    { class: "text-gray-700", description: "Text color: Gray 700" },
    { class: "text-gray-900", description: "Text color: Gray 900" },
    { class: "bg-white", description: "Background color: White" },
    { class: "bg-gray-50", description: "Background color: Gray 50" },
    { class: "bg-gray-100", description: "Background color: Gray 100" },
    { class: "bg-blue-500", description: "Background color: Blue 500" },
  ],
  flexbox: [
    { class: "items-center", description: "Align items: center" },
    { class: "justify-center", description: "Justify content: center" },
    { class: "justify-between", description: "Justify content: space-between" },
    { class: "flex-row", description: "Flex direction: row" },
    { class: "flex-col", description: "Flex direction: column" },
  ],
};
